<a href="https://colab.research.google.com/github/matteo9903/FCC/blob/main/Basics_of_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Un tensore è un **array con spedifiche dimensioni**


*   O-D --> **6** (semplice numero)
*   1-D --> **[1 0 -2]** (array)
*   2-D --> **MATRICE** (raggruppamento di tensori 1-D)  --> righe/colonne
*   3-D --> estensioni nella terza dimensione dei tensori 2-D



1-D = [1 0 -2]  --> dimensioni (3,)<br>
2-D = dimensioni (4,3) <br>| 1  2  0 |<br>
      | 0  4 -2 |<br>
      | 2  3  8 |<br>
      | 4  5  1 |<br><br>
3-D = es. (3,3,2) --> secondo e terzo numero sono le dimensioni delle matrici, il primo sono il loro numero

In [1]:
# IN COLAB NON SERVE INSTALLARE PACCHETTI
import tensorflow as tf

In [2]:
tensor_0d = tf.constant(3)
tensor_0d
# non ho shape ed è di tipo int32

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
tensor_1d = tf.constant([1,0.,-2])
tensor_1d
# vedo dimensione come ci si aspetta e tipo di contenuto (int, float...)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.,  0., -2.], dtype=float32)>

In [11]:
tensor_2d = tf.constant([[1,2,0],[0,4.1,-2],[2,3,8],[4,5,1]])
tensor_2d
# ho tensori 1D che raggruppati ne formano uno 2D

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1. ,  2. ,  0. ],
       [ 0. ,  4.1, -2. ],
       [ 2. ,  3. ,  8. ],
       [ 4. ,  5. ,  1. ]], dtype=float32)>

In [8]:
tensor_3d = tf.constant([[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]])
tensor_3d
# ho tensori 2D che ne formano uno 3D estendendosi nella terza dimensione

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 5],
        [3, 4, 6]],

       [[5, 6, 7],
        [7, 8, 9]]], dtype=int32)>

In [12]:
# posso stmpare dimensioni di ciascun tensore
print(tensor_0d.shape)  # 0D
print(tensor_1d.shape)  # 1D
print(tensor_2d.shape)  # 2D
print(tensor_3d.shape)   # 3D

()
(3,)
(4, 3)
(2, 2, 3)


può anche esistere un **tensore 4-D** formato da tensori 3-D "impilati" uno sull'altro

In [13]:
tensor_4d = tf.constant([[[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]],
 [[[9,8,7],[2,3,1]],[[10.2,0,-1],[7,4,9]]]])
tensor_4d

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[ 1. ,  2. ,  5. ],
         [ 3. ,  4. ,  6. ]],

        [[ 5. ,  6. ,  7. ],
         [ 7. ,  8. ,  9. ]]],


       [[[ 9. ,  8. ,  7. ],
         [ 2. ,  3. ,  1. ]],

        [[10.2,  0. , -1. ],
         [ 7. ,  4. ,  9. ]]]], dtype=float32)>

in base alla tipologia di applicazioni e alle risorse disponibili, si può eventualmente cambiare il formato dei dati (es. float16 vs float32 vs float64).<br> Vedi *documentazione Python* per verificare i tipi di dati disponibili)

In [14]:
 # posso anche specificare nell'intestazioni la tipolgoia di dato che voglio)
tensor_1d = tf.constant([1, -3, 0, 7, 2], dtype=tf.float32)
# tensor_1d = tf.constant([1, -3, 0, 7, 2], dtype=tf.float16)
tensor_1d

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1., -3.,  0.,  7.,  2.], dtype=float32)>