<a href="https://colab.research.google.com/github/matteo9903/FCC/blob/main/CORSO%20DL/Basics_of_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Un tensore è un **array con spedifiche dimensioni**


*   O-D --> **6** (semplice numero)
*   1-D --> **[1 0 -2]** (array)
*   2-D --> **MATRICE** (raggruppamento di tensori 1-D)  --> righe/colonne
*   3-D --> estensioni nella terza dimensione dei tensori 2-D



1-D = [1 0 -2]  --> dimensioni (3,)<br>
2-D = dimensioni (4,3) <br>| 1  2  0 |<br>
      | 0  4 -2 |<br>
      | 2  3  8 |<br>
      | 4  5  1 |<br><br>
3-D = es. (3,3,2) --> secondo e terzo numero sono le dimensioni delle matrici, il primo sono il loro numero

In [1]:
# IN COLAB NON SERVE INSTALLARE PACCHETTI
import tensorflow as tf

In [2]:
tensor_0d = tf.constant(3)
tensor_0d
# non ho shape ed è di tipo int32

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
tensor_1d = tf.constant([1,0.,-2])
tensor_1d
# vedo dimensione come ci si aspetta e tipo di contenuto (int, float...)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.,  0., -2.], dtype=float32)>

In [4]:
tensor_2d = tf.constant([[1,2,0],[0,4.1,-2],[2,3,8],[4,5,1]])
tensor_2d
# ho tensori 1D che raggruppati ne formano uno 2D

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1. ,  2. ,  0. ],
       [ 0. ,  4.1, -2. ],
       [ 2. ,  3. ,  8. ],
       [ 4. ,  5. ,  1. ]], dtype=float32)>

In [5]:
tensor_3d = tf.constant([[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]])
tensor_3d
# ho tensori 2D che ne formano uno 3D estendendosi nella terza dimensione

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 5],
        [3, 4, 6]],

       [[5, 6, 7],
        [7, 8, 9]]], dtype=int32)>

In [6]:
# posso stmpare dimensioni di ciascun tensore
print(tensor_0d.shape)  # 0D
print(tensor_1d.shape)  # 1D
print(tensor_2d.shape)  # 2D
print(tensor_3d.shape)   # 3D

()
(3,)
(4, 3)
(2, 2, 3)


può anche esistere un **tensore 4-D** formato da tensori 3-D "impilati" uno sull'altro

In [7]:
tensor_4d = tf.constant([[[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]],
 [[[9,8,7],[2,3,1]],[[10.2,0,-1],[7,4,9]]]])
tensor_4d

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[ 1. ,  2. ,  5. ],
         [ 3. ,  4. ,  6. ]],

        [[ 5. ,  6. ,  7. ],
         [ 7. ,  8. ,  9. ]]],


       [[[ 9. ,  8. ,  7. ],
         [ 2. ,  3. ,  1. ]],

        [[10.2,  0. , -1. ],
         [ 7. ,  4. ,  9. ]]]], dtype=float32)>

in base alla tipologia di applicazioni e alle risorse disponibili, si può eventualmente cambiare il formato dei dati (es. float16 vs float32 vs float64).<br> Vedi *documentazione Python* per verificare i tipi di dati disponibili)

In [8]:
 # posso anche specificare nell'intestazioni la tipolgoia di dato che voglio)
tensor_1d = tf.constant([1, -3, 0, 7, 2], dtype=tf.float32)
# tensor_1d = tf.constant([1, -3, 0, 7, 2], dtype=tf.float16)
tensor_1d

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1., -3.,  0.,  7.,  2.], dtype=float32)>

In [11]:
# errore perché 0. è considerato un float
tensor_1d = tf.constant([2, 0., -3, 8, 90], dtype=tf.int64)
print(tensor_1d)

TypeError: Cannot convert [2, 0.0, -3, 8, 90] to EagerTensor of dtype int64

In [12]:
# no errore perché ho float come dtype
tensor_1d = tf.constant([2, 0., -3, 8, 90], dtype=tf.float32)
print(tensor_1d)

# per avere numeri interi devo fare CASTING (può essere fatto con qualsiasi tipo
# di dati --> es. se metto "bool" avrò True/False se numero è >0)
tensor_1d_casted = tf.cast(tensor_1d, dtype=tf.int32)
print(tensor_1d_casted)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [13]:
# TENSORE BOOLEANO
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [14]:
# TENSORE STRINGA
tensor_string = tf.constant(["ciao", "come", "stai"])
print(tensor_string)

# stringhe sono precedute da "b", ovvero che sono immagazzinate come bytes,
# stringhe grezze, senza codici unicode


tf.Tensor([b'ciao' b'come' b'stai'], shape=(3,), dtype=string)


In [16]:
import numpy as np

##### Convert to tensor

In [17]:
# convert_to_tensor method
np_array = np.array([1,2,4])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


##### Eye tensor (matrice identità)

In [22]:
# EYE TENSOR --> matrice identità
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,  # None = matrice quadrata, altrimenti rettangolare
    batch_shape=[2,],  # None = un solo tensore; altrimenti matrice 3-D
    dtype=tf.dtypes.float32,  # definisco tipo di dato della matrice
    name=None
)
print(2*eye_tensor)

tf.Tensor(
[[[2. 0. 0. 0. 0.]
  [0. 2. 0. 0. 0.]
  [0. 0. 2. 0. 0.]
  [0. 0. 0. 2. 0.]
  [0. 0. 0. 0. 2.]]

 [[2. 0. 0. 0. 0.]
  [0. 2. 0. 0. 0.]
  [0. 0. 2. 0. 0.]
  [0. 0. 0. 2. 0.]
  [0. 0. 0. 0. 2.]]], shape=(2, 5, 5), dtype=float32)


##### Fill method

In [31]:
# FILL = crea tensore con lo stesso valore
fill_tensor = tf.fill(
      dims=[2,5,5],
      value=2,
      name=None
)
print(fill_tensor)

tf.Tensor(
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]], shape=(2, 5, 5), dtype=int32)


##### Ones method

In [34]:
# METODO ONES = matrice di 1
ones_tensor = tf.ones(
      shape=[2,5,5],
      dtype = tf.float32,
      name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 5, 5), dtype=float32)


In [37]:
# ONES LIKE = tensore di 1 con stessa dimensione dell'input
fill_ones_tensor = tf.ones_like(
    input = fill_tensor,  # prende dimensioni di fill_tensor (5x5)
    dtype=tf.int16,
    name=None
)
print(fill_ones_tensor)


tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(2, 5, 5), dtype=int16)


##### Zeros

In [42]:
# METODO ZEROS = matrice di 0
zeros_tensor = tf.zeros(
      shape=[2,5,5],
      # dtype = tf.float32,
      dtype = tf.dtypes.float32,
      name=None
)
print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(2, 5, 5), dtype=float32)


### -------------------------------------------------------------------

In [39]:
# SHAPE = dimensioni tensore
print(tensor_2d.shape)

(4, 3)


In [40]:
# RANK = rango matrice/tensore
print(tf.rank(tensor_2d))

tf.Tensor(2, shape=(), dtype=int32)


In [43]:
# SIZE = numero elementi nel tensore (es. righe*colonne nel caso 2-D)
print(tf.size(tensor_2d))
print(tf.size(tensor_2d, out_type=tf.float32))# posso anche decidere formato dell'output

tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(12.0, shape=(), dtype=float32)


##### Tensore random (tf.random)

Posso scgeliere da che distribuzione prenderla

In [48]:
# DISTRIBUZIONE NORMALE
# scelgo parametri della distribuzione normale (media e dev. standard)
# e dimensione del tensore
random_tensor = tf.random.normal(
    shape=(3,3),
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 0.6934901  -0.71436554 -0.8947401 ]
 [-0.10563215 -1.4560245   0.5881198 ]
 [ 0.83072144  0.9920155  -0.34359917]], shape=(3, 3), dtype=float32)


In [54]:
random_uniform_tensor = tf.random.uniform(
    shape=(3,3),
    minval=0,
    maxval=8,   # None = 1 (oppure default)
    dtype=tf.dtypes.float32,
    seed=10,  #  SEED --> serve a creare risultati riproducibili in chiamate
    name=None           #  multiple
)
print(random_uniform_tensor)
# anche impostando seme risultati sono diversi

tf.Tensor(
[[7.144147   0.44688606 5.1351995 ]
 [1.4417448  3.6194477  6.5432854 ]
 [5.2268915  4.364249   4.253787  ]], shape=(3, 3), dtype=float32)


In [57]:
# per avere risultati deterministici al massimo, bisogna impostare i valori
# globali del seed
tf.random.set_seed(11)


new_random_uniform_tensor = tf.random.uniform(
    shape=(3,3),
    minval=0,
    maxval=8,   # None = 1 (oppure default)
    dtype=tf.dtypes.float32,
    seed=10,  #  SEED --> serve a creare risultati riproducibili in chiamate
    name=None           #  multiple
)
print(new_random_uniform_tensor)

tf.Tensor(
[[5.63997    2.6964722  4.532753  ]
 [3.5593653  6.587965   1.2875919 ]
 [5.958709   7.620591   0.29762936]], shape=(3, 3), dtype=float32)


### Tensor Indexing

In [59]:
tensor_indexed = tf.constant([1,5,2,18,0,-4])
print(tensor_indexed)
print(tensor_indexed[0:3]) # tensori 1-D trattati come array
print(tensor_indexed[0:-2]) # tensori 1-D trattati come array

tf.Tensor([ 1  5  2 18  0 -4], shape=(6,), dtype=int32)
tf.Tensor([1 5 2], shape=(3,), dtype=int32)
tf.Tensor([ 1  5  2 18], shape=(4,), dtype=int32)


In [60]:
tensor_2d = tf.constant([[1,2,0],[0,4.1,-2],[2,3,8]])
print(tensor_2d[0:3, 0:2])  # tratto tensore 2-D come matrice (riga , colonna)

tf.Tensor(
[[1.  2. ]
 [0.  4.1]
 [2.  3. ]], shape=(3, 2), dtype=float32)


In [64]:
tensor_3d = tf.constant([[[1,2,5],[3,4,6]],[[5,6,7],[7,8,9]]])
print(tensor_3d[0:2, 1:3, 1:2]) # II riga e II colonna dei singoli tensori 2-D
# prendo elemento specifico a caso
print(tensor_3d[1, 1, 2])

tf.Tensor(
[[[4]]

 [[8]]], shape=(2, 1, 1), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### Math operations (tf.math)

In [74]:
# VALORE ASSOLUTO
x = tf.constant([[1,-2,3],[-4,5,-6]])
x_abs = tf.math.abs(x)
x_abs = tf.cast(x_abs, dtype=tf.float32)
print(x_abs)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [66]:
# VALORE ASSOLUTO NUMERI COMPLESSI (a + bj --> abs = sqrt(a^2 + b^2) )
x_complex = tf.constant([(1+2j), (3+4j)])
x_abs_complex = tf.math.abs(x_complex)
print(x_abs_complex)

tf.Tensor([2.23606798 5.        ], shape=(2,), dtype=float64)


In [76]:
# RADICE QUADRATA
# devo avere numeri float
x_sqrt = tf.math.sqrt(x_abs) # math posso anche ometterlo
print(x_sqrt)

tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.2360678 2.4494896]], shape=(2, 3), dtype=float32)


In [96]:
# OPERAZIONI ARITMETICHE
a = tf.constant([[1,2,5],[3,4,6]])
b = tf.constant([[5,6,7],[7,8,9]])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b)) # prodotto elemento per elemento
print(tf.divide(a,b))
print(tf.math.pow(a,b))
# print(tf.math.add(a,b))

tf.Tensor(
[[ 6  8 12]
 [10 12 15]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-4 -4 -2]
 [-4 -4 -3]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 5 12 35]
 [21 32 54]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.2        0.33333333 0.71428571]
 [0.42857143 0.5        0.66666667]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[       1       64    78125]
 [    2187    65536 10077696]], shape=(2, 3), dtype=int32)


In [82]:
# DIVIDE NO NAN = consente divisione restituisce 0 se si divide per 0
x_1 = tf.constant([1,2,5], dtype=tf.float32)
x_2 = tf.constant([0,2,0], dtype=tf.float32)
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)


##### Broadcasting
È importante che entrambi i tensori **abbiano almeno una dimensione unitaria** (non importa se riga/colonna)

In [86]:
# ho tensore più piccolo che viene espanso a tutti gli altri elementi
# del tensore più grande , effettuando operazioni di conseguenza

x_1 = tf.constant([53,6,4,6], dtype = tf.float32)
x_2 = tf.constant([2], dtype = tf.float32)
print(tf.math.add(x_1, x_2))

tf.Tensor([55.  8.  6.  8.], shape=(4,), dtype=float32)


In [88]:
x_1 = tf.constant([[5,4,3,2,6]], dtype = tf.float32)
x_2 = tf.constant([[2], [2], [1]], dtype = tf.float32)
print(tf.math.multiply(x_1, x_2))

tf.Tensor(
[[10.  8.  6.  4. 12.]
 [10.  8.  6.  4. 12.]
 [ 5.  4.  3.  2.  6.]], shape=(3, 5), dtype=float32)


In [90]:
# MAXIMUM = prendo valori massimi fra i 2 tensori nelle specifiche posizioni
x_1 = tf.constant([[-2,4,3,2,6]], dtype = tf.float32)
x_2 = tf.constant([[5,0,1,6,1]], dtype = tf.float32)
print(tf.math.maximum(x_1, x_2))

tf.Tensor([[5. 4. 3. 6. 6.]], shape=(1, 5), dtype=float32)


In [93]:
# ARGMAX = indice del valore massimo di ogni riga/colonna
x_argmax = tf.constant([[1,2,5],[3,4,6], [9,1,0]])
print(tf.math.argmax(x_argmax, axis=1))  # prendo indice del massimo di ogni riga
print(tf.math.argmax(x_argmax, axis=0))  # stesso per le colonne

tf.Tensor([2 2 0], shape=(3,), dtype=int64)
tf.Tensor([2 1 1], shape=(3,), dtype=int64)


In [95]:
# COMPARE = paragono due tensori, anche qua vale broadcasting
# viene fatta uguaglianza elemento per elemento
x = tf.constant([[1,5,1], [6,1,0], [0, 9, 5]])
y = tf.constant([[1,5,1], [6,1,0], [0, 9, 5]])
y_1 = tf.constant([[1,9,4], [6,7,2], [0, 8, 5]])

print(tf.math.equal(x,y))
print(tf.math.equal(x,y_1))

tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[ True False False]
 [ True False False]
 [ True False  True]], shape=(3, 3), dtype=bool)


In [105]:
# REDUCE SUM = somma di tutti gli elementi all'interno del tensore (senza
# distinguere fra riga e colonna)
input_tensor = tf.constant([[1,-5,5],[3,4,6]], dtype = tf.float32)
print(tf.math.reduce_sum(input_tensor))
# se specifico asse faccio somma per colonne (axis=0) o per righe (axis=1)
# keepdims --> se True, faccio flattening del risultato, altrimenti mantengo
#              le dimensioni originali e risultato è array con una riga/colonna
#              di dimensione unitaria
print(tf.math.reduce_sum(input_tensor, axis = 0, keepdims = True))
print(tf.math.reduce_sum(input_tensor, axis = 1, keepdims = False))


# REDUCE MAX/MIN = massimo/minimo globale della matrice
print(tf.math.reduce_max(input_tensor))
print(tf.math.reduce_min(input_tensor))
# POSSO FARE ANCHE DEVIAZIONE STANDARD/MEDIA....
print(tf.math.reduce_std(input_tensor))
print(tf.math.reduce_mean(input_tensor))

tf.Tensor(14.0, shape=(), dtype=float32)
tf.Tensor([[ 4. -1. 11.]], shape=(1, 3), dtype=float32)
tf.Tensor([ 1. 13.], shape=(2,), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(-5.0, shape=(), dtype=float32)
tf.Tensor(3.6362374, shape=(), dtype=float32)
tf.Tensor(2.3333333, shape=(), dtype=float32)


##### Top K
prendo i K valori più grandi per ogni riga (ordinati in maniera decrescente di default)

In [110]:
tensor_2d = tf.constant([[1,2,0],[0,4.1,-2],[2,3,1]], dtype=tf.float32)
# print(tf.math.top_k(tensor_2d, k=2, sorted=False)) # rimuovo ordinamento
print(tf.math.top_k(tensor_2d, k=2))

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2. , 1. ],
       [4.1, 0. ],
       [3. , 2. ]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [1, 0]], dtype=int32)>)


### Operazioni di algebra lineare (tf.linalg)


In [117]:
# MATMUL = moltiplicazione fra matrici
# possibile solo se colonne I matrice = righe II matrice
x_1 = tf.constant([[1,2,2], [4,0,1], [7, 0, 4]])
x_2 = tf.constant([[7,1,6], [4,6,1], [7, 0, 4]])

print(tf.linalg.matmul(x_1, x_2, transpose_a = False, transpose_b=True,
                       a_is_sparse=False, b_is_sparse=False, adjoint_a=False,
                       adjoint_b=False, output_type=None, name=None))
print(x_1@x_2) # stesso risultato (nessuna trasposizione)

tf.Tensor(
[[21 18 15]
 [34 17 32]
 [73 32 65]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[29 13 16]
 [35  4 28]
 [77  7 58]], shape=(3, 3), dtype=int32)


In [114]:
# TRASPOSIZIONE
print(x_1)
print(tf.transpose(x_1))

tf.Tensor(
[[1 2 2]
 [4 0 1]
 [7 0 4]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 4 7]
 [2 0 0]
 [2 1 4]], shape=(3, 3), dtype=int32)


##### Prodotto con matrici multidimensionali
logica è moltiplicare la prima matrice del sottogruppo con la prima
del sottogruppo dell'altra matrice, e così via con le altre

In [118]:
x_1_3d = tf.constant([[[1,2,2], [4,0,1], [7, 0, 4]],
                      [[1,2,2], [4,0,1], [7, 0, 4]],
                      [[0,4,3], [1,1,1], [4,6,-2]]])
x_2_3d = tf.constant([[[7,1,6], [4,6,1], [7, 4, 4]],
                      [[7,8,2], [4,3,7], [9, 1, 2]],
                       [[9,6,2], [4,9,1], [7, 4, 2]]])

print(x_1_3d@x_2_3d)

tf.Tensor(
[[[29 21 16]
  [35  8 28]
  [77 23 58]]

 [[33 16 20]
  [37 33 10]
  [85 60 22]]

 [[37 48 10]
  [20 19  5]
  [46 70 10]]], shape=(3, 3, 3), dtype=int32)


### Sparse tensors

se viene specificato che tensore è sparso (maggioranza elementi 0), Tensorflow lo sa e dunque ottimizza i calcoli apposta per questa categoria di matrici (che altrimenti richiederebbe troppe risorse inutili in eccesso)