<a href="https://colab.research.google.com/github/matteo9903/FCC/blob/main/CORSO%20DL/Main%20functions%20of%20TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Main TensorFlow functions

In [2]:
import tensorflow as tf

In [6]:
X = tf.constant(
    [[1,5,6],
     [4,8,9],
     [1,0,5]]
)

In [15]:
 #### EXPAND DIMS
 # aggiungo dimensione unitaria extra
 # axis --> specifico in che dimensione la voglio inserire (0 a N_dims)
 # ------------------------------------------
X_expanded = tf.expand_dims(X, axis=1)
X_expanded
# (3,3) --> (1,3,3)

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 5, 6]],

       [[4, 8, 9]],

       [[1, 0, 5]]], dtype=int32)>

In [11]:
 #### SQUEEZE DIMS
 # rimuovo dimensione unitaria extra
 # axis --> specifico in che dimensione la voglio rimuovere (0 a N_dims)
 # ------------------------------------------
tf.squeeze(X_expanded, axis=0)
 # (1,3,3) -> (3,3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 5, 6],
       [4, 8, 9],
       [1, 0, 5]], dtype=int32)>

In [18]:
tf.expand_dims(X, axis=1)
# (3,3) --> (1,3,3)  axis = 0
# (3,3) --> (3,1,3)  axis = 1
# (3,3) --> (3,3,1)  axis = 2


<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 5, 6]],

       [[4, 8, 9]],

       [[1, 0, 5]]], dtype=int32)>

In [24]:
#### RESHAPE
# modifico dimensione tensore
# !! DEVONO ESSERE VALORI AMMISSIBILI PER LE DIM DELLA MATRICE !!
# ------------------------------------------
print(tf.reshape(X_expanded, shape=(3,3)))  # può fungere da squeeze

print("---------------------------------")
# flattening della matrice (3x3 = 9)
print(tf.reshape(X_expanded, shape=(1,9)))
# flattening della matrice (3x3 = 9) (solo vettore), -1 è riconosciuto come 9
print(tf.reshape(X_expanded, shape=(-1)))
print("---------------------------------")
A = tf.constant([[2,3,1,0], [4,5,6,7]])
# se matrice non quadrata, invertire dimensioni genera la trasposta
print(tf.reshape(A, shape=(4,2)))
# mettere -1 è uguale perché è l'ultima colonna
print(tf.reshape(A, shape=(4,-1)))


tf.Tensor(
[[1 5 6]
 [4 8 9]
 [1 0 5]], shape=(3, 3), dtype=int32)
---------------------------------
tf.Tensor([[1 5 6 4 8 9 1 0 5]], shape=(1, 9), dtype=int32)
tf.Tensor([1 5 6 4 8 9 1 0 5], shape=(9,), dtype=int32)
---------------------------------
tf.Tensor(
[[2 3]
 [1 0]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [1 0]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
